version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: nuget
    directory: /src/api-dotnet
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      api-nuget-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: nuget
    directory: /tests/api-dotnet
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      test-nuget-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: pip
    directory: /src/ai-service-python
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      python-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /src/api-dotnet
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "dotnet/sdk"
        versions:
          - "9.x"
      - dependency-name: "dotnet/aspnet"
        versions:
          - "9.x"

  - package-ecosystem: docker
    directory: /src/ai-service-python
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
